# Generated by Django 4.1.7 on 2023-03-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_customer_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="order",
            name="vat",
            field=models.FloatField(default=0.2),
        ),
    ]
